name = "policychecker"
version = "0.1.0"
defaultTargets = ["policychecker"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "PolicyChecker"
roots = ["PolicyChecker"]

[[lean_exe]]
name = "policychecker"
root = "LeanMain"
supportInterpreter = true
